using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "MemberInfo", menuName = "My Game/Member Info")]
public class MemInfo : ScriptableObject
{
    public string[] names = new string[] { "Isaac ♂", "Abel ♂", "Zacharias ♂", "Eloise ♀", "Deborah ♀", "Benjamin ♂", "Adam ♂", "Abraham ♂", "Methuselah ♂", "Bertha ♀", "Bartholomew ♂", "Elijah ♂", "Elon ♂", "Ezekiel ♂", "Gabriel ♂", "Aaron ♂", "Luna ♀", "Immanuel ♂", "Ishmael ♂", "Lily ♀", "Jacob ♂", "Joel ♂", "Narcisa ♀", "Joseph ♂", "Joshua ♂", "Levi ♂", "Lucas ♂", "Minerva ♀", "Moses ♂", "Noah ♂", "Rufus ♂", "Samson ♂", "Seth ♂", "Solomon ♂", "Timothy ♂", "Neville ♂", "Bathilda ♀", "Amelia ♀", "Susan ♀", "Charity ♀", "Fleur ♀", "Ariana ♀", "Petunia ♀", "Olivia ♀", "Molly ♀", "Myrtle ♀", "Ginny ♀", "Andromeda ♀", "Dolores ♀", "Rita ♀", "Aurora ♀", "Mafalda ♀", "Graham ♂", "Theodore ♂", "Felix ♂", "Silas ♂", "Oliver ♂", "Hugo ♂", "Oscar ♂", "Edgar ♂", "August ♂", "Jasper ♂", "Otto ♂", "Theo ♂", "Cyrus ♂", "Sebastian ♂", "Henry ♂", "Otis ♂", "Tobias ♂", "Nathaniel ♂", "Arthur ♂", "Emmett ♂", "Florence ♂", "Julian ♂", "Samuel ♂", "Lawrence ♂", "Frederick ♂", "Winifred ♂", "Agnes ♀", "Emma ♀", "Catherine ♀", "Vera ♀", "Daisy ♀", "Elsie ♀", "Sophie ♀", "Ella ♀", "Ruby ♀", "Willa ♀", "Mary ♀", "Flora ♀", "Esther ♀", "Anna ♀", "Ivy ♀", "Annabelle ♀", "Cecilia ♀", "Adeline ♀", "Adele ♀", "Louis ♂","Ash ♀", "Mathilda ♀", "Adelaide ♀", "Cordelia ♀", "Ophelia ♀", "Alice ♀", "Eleanor ♀", "Violet ♀", "Charlotte ♀", "Clara ♀", "Amadeus ♂", "Boris ♂", "Gaspar ♂", "Ismael ♂", "Leopold ♂", "Alessandro ♂", "Rome ♂", "Valentine ♀", "Constance ♀", "Frieda ♀", "Greta ♀", "Ines ♀", "Margarita ♀", "Magdalene ♀", "Rose ♀", "Rufina ♀", "Camila ♀", "Gabriela ♀", "Sara ♀", "Mariana ♀", "Barbara ♀", "Antonia ♀", "Fernanda ♀", "Lucy ♀", "Renatus ♂", "Ludo ♂", "Phineas ♂", "Percival ♂", "Fred ♂", "Charlie ♂", "Ted ♂", "Dean ♂", "Pius ♂", "Horace ♂", "Stan ♂", "Albert ♂", "Galileo ♂", "Ernie ♂", "Lucian ♂", "Gilderoy ♂", "Victor ♂", "Igor ♂", "Cornelius ♂", "Cedric ♂", "Dick ♂", "Barty ♂", "Colin ♂", "Terry ♂", "Cassiopeia ♀", "Cosette ♀", "Elvira ♀", "Misty ♀", "Chaplin ♂", "Faramir ♂", "Leo ♂", "Edmund ♂", "Dimitri ♂", "Columbus ♂", "Chadwick ♂", "Bertie ♂", "Amos ♂", "Alphonso ♂", "Adolphus ♂", "Eugene ♂", "Gonzalo ♂", "Hudson ♂", "Ignatius ♂", "Irven ♂", "Jackson ♂", "Joaquin ♂", "Jonas ♂", "Julius ♂", "Kale ♂", "Lazarus ♂", "Leonidas ♂", "Lucius ♂", "Marcelino ♂", "Miles ♂", "Moises ♂", "Morgan ♂", "Mustafa ♂", "Montgomery ♂", "Newton ♂", "Norberto ♂", "Norris ♂", "Octavio ♂", "Orlando ♂", "Porter ♂", "Ramsey ♂", "Rupert ♂", "Rex ♂", "Sergio ♂", "Santiago ♂", "Gordon ♂", "Spenser ♂", "Sullivan ♂", "Tito ♂", "Trinity ♀", "Vito ♂", "Washington ♂", "Alba ♀", "Albina ♀", "Beatrice ♀", "Evelyn ♀", "Katarina ♀", "Tristana ♀", "Tristan ♂", "Jupiter ♀", "Holly ♀", "Bellamy ♀", "Salem ♀", "Sol ♀", "Alexis ♀", "Alexis ♂", "Logan ♂", "Phoenix ♂", "Rowan ♂", "Dakota ♀", "Skylar ♀", "Jessie ♀", "Jackie ♀", "Frankie ♀", "Angel ♀", "Sammie ♀", "Robbie ♀", "Noelle ♀", "Ariel ♀", "Rene ♀", "Elliot ♂", "Consuelo ♀", "Chiquita ♀", "Delphine ♀", "Emily ♀", "Euphemia ♀", "Fanny ♀", "Georgina ♀", "Grace ♀", "Hannah ♀", "Indiana ♀", "Lola ♀", "Jasmine ♀", "Earl ♂", "Johana ♀", "Juana ♀", "Lindy ♀", "Lorelei ♀", "Manuela ♀", "Naomi ♀", "Nikita ♀", "Penelope ♀", "Phebe ♀", "Petra ♀", "Paulina ♀", "Rhianna ♀", "Rosalinda ♀", "Samara ♀", "Tamara ♀", "Simone ♀", "Tatianna ♀", "Theodora ♀", "Vanessa ♀", "Pamela ♀", "Vladimir ♂", "Aristotle ♂", "Plato ♂", "Socrates ♂", "Martin ♂", "Ludwig ♂", "Nicolaus ♂", "Sigmund ♂", "Nelson ♂", "Voltaire ♂", "Wolfgang ♂", "Napoleon ♂", "Elvis ♂", "Michelangelo ♂", "Ulysses ♂", "Shakespeare ♂", "Winston ♂", "Kennedy ♂", "Donald ♂", "Franklin ♂", "Walt ♂", "Barack ♂", "Obama ♂", "Malcolm ♂", "Ford ♂", "Fidel ♂", "Picasso ♂", "Alfred ♂", "Usain ♂", "Roger ♂", "Desmond ♂", "Lance ♂", "Ernest ♂", "Sasha ♀", "Shakira ♀", "Antoinette ♀", "Audrey ♀", "Lionel ♂", "Madonna ♀", "Eva ♀", "Marilyn ♀", "Rutherford ♂", "Chester ♂", "Cleveland ♂", "Roosevelt ♂", "Herbert ♂", "Truman ♂", "Eisenhower ♂", "Nixon ♂", "Carter ♂", "Ron ♂", "Clinton ♂", "Erika ♀", "Sabrina ♀", "Giovanni ♂", "Morty ♂", "Chuck ♂", "Claire ♀", "Roxanne ♀", "Watson ♂", "Norman ♂", "Wallace ♂", "Fatima ♀", "Wulfric ♂", "Valerie ♀", "Olympia ♀", "Marnie ♀", "Allan ♂", "Friedrich ♂", "Max ♂", "Monty ♂", "Horatio ♂", "Gerard ♂", "Agatha ♀", "Clarence ♀", "Dorian ♂", "Niels ♂", "Drake ♂", "Bertrand ♂", "Merlin ♂", "Lancelot ♂", "Babel ♂", "Claudius ♂", "Remus ♂", "Romulus ♂", "Basilio ♂", "Sid ♂", "Dennis ♂", "Ed ♂", "Bart ♂", "Paganini ♂", "Parisa ♀", "Vivaldi ♂", "Erwin ♂", "Braun ♂", "Harambe ♂", "Pelé ♂", "Koko ♂", "Sedna ♀", "Alastor ♂", "Midna ♀", "Juno ♂", "Neptune ♂", "Venus ♀", "Apollo ♂", "Saturn ♂", "Artemis ♀", "Athena ♀", "Hermes ♂", "Zeus ♂", "Dionysus ♂", "Avril ♀", "Salvador ♂", "Adela ♀", "Blanca ♀", "Estrella ♀", "Luz ♀", "Angelina ♀", "Caroline ♀", "Esmeralda ♀", "Felicity ♀", "Paloma ♀", "Ramona ♀", "Ramon ♂", "Belen ♀", "Josefina ♀", "Teresa ♀", "Summer ♀", "Omar ♂", "Bonnie ♀", "Carmen ♀", "Michael ♂", "Paolo ♂", "Christopher ♂", "Jessica ♀", "Matthew ♂", "Ashley ♀", "Jennifer ♀", "Louise ♀", "Amanda ♀", "Daniel ♂", "David ♂", "James ♂", "Robert ♂", "Alonso ♂", "John ♂", "Andrew ♂", "Ryan ♂", "Franco ♂", "Brandon ♂", "Jason ♂", "Claribel ♀", "Justin ♂", "Sarah ♀", "William ♂", "Jonathan ♂", "Stephanie ♀", "Brian ♂", "Nicole ♀", "Nicholas ♂", "Anthony ♂", "Heather ♀", "Eric ♂", "Elizabeth ♀", "Megan ♀", "Melissa ♀", "Lucien ♂", "Kevin ♂", "Thomas ♂", "Christina ♀", "Kyle ♂", "Rachel ♀", "Laura ♀", "Lauren ♀", "Amber ♀", "Brittany ♀", "Danielle ♀", "Richard ♂", "Kimberly ♀", "Jeffrey ♂", "Amy ♀", "Crystal ♀", "Michelle ♀", "Tiffany ♀", "Jeremy ♂", "Mark ♂", "Charles ♂", "Rebecca ♀", "Stephen ♂", "Patrick ♂", "Sean ♂", "Erin ♀", "Jamie ♀", "Kelly ♀", "Samantha ♀", "Nathan ♂", "Dustin ♂", "Paul ♂", "Allegra ♀", "Hamilton ♂", "Angela ♀", "Marlon ♂", "Tyler ♂", "Scott ♂", "Katherine ♀", "Andrea ♀", "Gregory ♂", "Erica ♀", "Rolanda ♀", "Travis ♂", "Lisa ♀", "Kenneth ♂", "Lindsey ♀", "Kristen ♀", "Jose ♂", "Alvaro ♂", "Alexander ♂", "Jesse ♀", "Katie ♀", "Raymond ♂", "Shannon ♀", "Courtney ♀", "Christine ♀", "Alicia ♀", "Cody ♂", "Allison ♀", "Shawn ♂", "Derek ♂", "Kristin ♀", "Chad ♂", "Jenna ♀", "Tara ♀", "Krystal ♀", "Jared ♂", "Edward ♂", "Julie ♀", "Peter ♂", "Marcus ♂", "Natalie ♀", "Jordan ♂", "Victoria ♀", "Jacqueline ♀", "Corey ♀", "Keith ♂", "Monica ♀", "Juan ♂", "Cassandra ♀", "Shane ♂", "Phillip ♂", "Patricia ♀", "Brett ♂", "Ronald ♂", "George ♂", "Antonio ♂", "Cynthia ♀", "Stacy ♀", "Kathleen ♀", "Carlos ♂", "Brandi ♀", "Douglas ♂", "Ian ♂", "Craig ♂", "Brandy ♀", "Alex ♂", "Veronica ♀", "Cory ♀", "Whitney ♀", "Gary ♂", "Derrick ♂", "Philip ♂", "Luis ♂", "Diana ♀", "Chelsea ♀", "Leslie ♀", "Caitlin ♀", "Leah ♀", "Natasha ♀", "Casey ♀", "Erik ♂", "Dana ♀", "Brent ♂", "Dominique ♂", "Frank ♂", "Brittney ♀", "Ewan ♂", "Julia ♀", "Candice ♀", "Karen ♀", "Melanie ♀", "Adrian ♀", "Stacey ♀", "Margaret ♀", "Sheena ♀", "Wesley ♂", "Vincent ♂", "Alexandra ♀", "Katrina ♀", "Bethany ♀", "Nichole ♀", "Larry ♂", "Jeffery ♀", "Curtis ♂", "Carrie ♀", "Todd ♂", "Blake ♂", "Christian ♂", "Randy ♂", "Alison ♀", "Trevor ♂", "Kara ♀", "Joanna ♀", "Luke ♂", "Felicia ♀", "Brooke ♂", "Austin ♂", "Candace ♀", "Jesus ♂", "Sandra ♀", "Tracy ♀", "Kayla ♀", "Nancy ♀", "Tina ♀", "Krystle ♀", "Russell ♂", "Jeremiah ♂", "Carl ♂", "Miguel ♂", "Tony ♂", "Gina ♀", "Jillian ♂", "Mitchell ♂", "Renee ♀", "Denise ♀", "Jerry ♂", "Mario ♂", "Johnathan ♂", "Jaclyn ♀", "Brenda ♀", "Lacey ♀", "Shaun ♂", "Devin ♂", "Heidi ♀", "Troy ♂", "Desiree ♀", "Andre ♂", "Miranda ♀", "Alyssa ♀", "Johnny ♂", "Tabitha ♀", "Ricardo ♂", "Chase ♂", "Melinda ♀", "Monique ♀", "Tanya ♀", "Linda ♀", "Bobby ♂", "Caleb ♂", "Ashlee ♀", "Kelli ♀", "Garrett ♂", "Mallory ♀", "Jill ♂", "Kristy ♀", "Francisco ♂", "Robin ♂", "Manuel ♂", "Meredith ♀", "Christy ♀", "Ricky ♂", "Randall ♂", "Marissa ♀", "Ross ♂", "Jimmy ♂", "Abigail ♀", "Kendra ♀", "Billy ♂", "Deanna ♀", "Jenny ♀", "Taylor ♂", "Lori ♀", "Rebekah ♀", "Cameron ♂", "Ebony ♀", "Wendy ♀", "Kristi ♀", "Francis ♂", "Dawn ♀", "Kari ♀", "Clayton ♂", "Roberto ♂", "Priscilla ♀", "Darren ♂", "Kelsey ♀", "Walter ♂", "Cassie ♀", "Grant ♂", "Cristina ♀", "Tonya ♀", "Rodney ♂", "Bridget ♀", "Joe ♂", "Cindy ♀", "Willie ♂", "Maurice ♂", "Jaime ♂", "Angelica ♀", "Sharon ♀", "Jack ♂", "Jay ♂", "Calvin ♂", "Hector ♂", "Kate ♀", "Adrienne ♀", "Tasha ♀", "Michele ♀", "Stefanie ♀", "Cara ♀", "Alejandro ♂", "Ruben ♂", "Gerald ♂", "Shana ♀", "Javier ♂", "Brianna ♀", "Bruce ♂", "Claudia ♀", "Carla ♀", "Wayne ♂", "Roy ♂", "Virginia ♀", "Haley ♂", "Brendan ♂", "Janelle ♀", "Beth ♀", "Edwin ♂", "Dylan ♂", "Dominic ♂", "Latasha ♀", "Darrell ♂", "Geoffrey ♂", "Reginald ♂", "Carly ♀", "Fernando ♂", "Aimee ♀", "Regina ♀", "Mandy ♀", "Raphael ♂", "Pedro ♂", "Janet ♀", "Smith ♂", "Johnson ♂", "Williams ♂", "Brown ♀", "Jones ♂", "Garcia ♂", "Davis ♂", "Rodriguez ♂", "Martinez ♂", "Hernandez ♀", "Lopez ♀", "Gonzalez ♂", "Wilson ♂", "Anderson ♂", "Lee ♂", "Perez ♂", "Thomson ♂", "Harris ♂", "Sanchez ♂", "Clark ♂", "Ramirez ♀", "Lewis ♀", "Robinson ♂", "Walker ♂", "Hill ♀", "Adams ♂", "Rivera ♀", "Gomez ♂", "Turner ♂", "Diaz ♀", "Parker ♂", "Stewart ♀", "Morris ♂", "Morales ♂", "Murphy ♂", "Gutierrez ♂", "Ortiz ♀", "Howard ♂", "Cooper ♂", "Peterson ♂", "Ramos ♂", "Kim ♀", "Chavez ♂", "Mendoza ♂", "Ruiz ♀", "Sanders ♂", "Foster ♂", "Jimenez ♀", "Anastasia ♀", "Pepe ♂", "Antoinette ♀", "Leonardo ♂", "Donatello ♂", "Belinda ♀", "Donatella ♀", "Celina ♀", "Amy ♀", "Luisa ♀", };

    public string[] traitList = new string[236]
    {
        "Genius", "Thick", "Hermit", "Cannibal", "Claustrophobic", "Hypochondriac", "Constipated", "Scared of the Dark", "Mysterious", "Glutton",
        "Rookie", "Rebel", "Prone to Panic Attacks", "Big D Energy", "Copycat", "Pervert", "Messy", "Competitive", "Dictator", "Quitter",
        "Pyromaniac", "Trips Over Easily", "Itchy Back", "Smelly Feet", "Fragile", "Slow Learner", "Magic Trick Enthusiast", "Moody", "Tardy", "Psychopath", "Senile",
        "War Fanatic", "Pacifist", "Tilter", "Thief", "Toxic", "Has an Imaginary Friend", "Flat Earther", "Unlucky", "Lucky", "Insecure", "Jealous Professional", "Elitist", "He Shits Himself", "Nervous Flirter", "Geek", "Serial Killer", "Vain",
        "Low Self-esteem", "Exhibitionist", "Empathetic", "Argumentative", "Bad Eyesight", "Centenarian", "Boss Wannabe", "Masochist", "Sadistic", "Could be 2 Kids in a Trenchcoat", "Cthulhu Worshipper", "Selfish", "Procrastinator",
        "Doppelganger Victim", "In Love", "Casanova", "Ex-partner", "Toxic Lover", "Martyr", "Bad Hygiene", "Anti-Masker", "Full of Shit", "Bully", "Friendzoned", "Old-fashioned", "Mr. Moneybags", "Drunkard", "Selfless", "Hero Mindset",
        "Unreliable", "Best buddies", "Emo", "Pregnant", "Has the Flu", "Uncontrollable Flatulences", "Ex-prisoner", "Spiritual Meditator", "Seasick", "Liar", "Can't Swim", "Has Explosive Diarrhoea", "Necromancy Enthusiast",
        "Has War Flashbacks", "Anti-Vaxxer","Traitor", "Undercover Competitor", "Hearing Loss", "Sensitive to Smells", "Has Gross Eating Habits", "Puppeteering Enthusiast", "Speaks like a Robot", "Snitch", "Porn Addict",
        "Enthusiastic handyman", "Avid Swimmer", "Cheeky Undergrad", "Parties Hard", "Passionate about Science", "Massage expert", "Chronic Masturbator", "Uncontrolled Illusionist", "Allergic to Seafood", "Having a Bad Break",
        "Escape artist", "Speaks Fish Language", "Usurper", "Global Warming Denier", "Unsure About their Profession", "Heavy Snoring", "Bodybuilder", "Alucard", "Ghost", "Stoned", "Insured Out of His Ass", "Hates Kids", "Thinks they're a Fish",
        "Supercentenarian", "Normal", "Expecting a Delivery", "Plays With Boogers", "He Pisses Himself", "Shoddy Plumber", "Cleaning Freak", "Sushi Chef", "One-trick Pony", "Short-tempered", "Easily Distracted", "Seafood Lover", "Ate an Expired Yoghurt",
        "Heavy Smoker", "Infested With Bedbugs", "Complacent", "Bone Architect", "Corpse Looter", "Unleashed Power", "Gruesome Body", "Easily Bored", "Obsessed Collector", "Has OCD", "Hired Assassin", "Scared of Heights", "Alien-looking",
        "Caveman", "Has had Plastic Surgery", "All-nighter Metalhead", "Sushi Lover", "Never Reads Manuals", "Home Chef", "Also a Bartender", "Also an Electrician", "Caregiver", "Also a Lawyer", "Titanic Connoisseur",
        "Funeral Organiser", "Frankestein Fan", "Also a Politician", "Also a Priest", "Cursed", "Posessed", "Constantly Picks their Scabs", "Has Amnesia", "Also a Veterinarian", "Apocalypse Paranoid", "Night Owl", "A Karen",
        "Loves Rainbows", "Big Fan", "BDSM Enthusiast", "Loves Comfort", "Professor", "Loves Fireworks", "Posh Millionaire", "Creepy Stalker", "Kidnapper", "Builds Ships in Bottles", "Gifted", "Recycling Fanatic", "Tap dance Enthusiast",
        "Hypothermic", "Radioactive", "Big Daddy", "Missing an arm and a leg",
        "Amateur Surgeon",
        "Learns From Mistakes",
        "Clumsy",
        "Uni-tasker",
        "Hoarder",
        "Generous",
        "Jealous",
        "Thinks This is All a Dream",
        "Emotionally Attached",
        "Sleepwalker",
        "Has Sweet Dreams",
        "Has Nightmares",
        "Does the Opposite",
        "Gambling Addict",
        "Expert Gardener ",
        "Forgetful",
        "Vegetarian",
        "Spits Fire",
        "Careless",
        "Babysitter",
        "Loves Ruins",
        "Repairman Wannabe",
        "Hates Society",
        "Isolationist",
        "Baker",
        "Orchestra Conductor",
        "Wimp",
        "Danger Addict",
        "No Driver’s Licence",
        "Environmentalist",
        "Allergic to Pollen",
        "Wood Sculptor",
        "Fire Fighter",
        "Coastguard",
        "High Body Temperature",
        "Loves Popsicles",
        "Hyperactive",
        "Deep Thinker",
        "Jungle Rescuer",
        "Marathon Runner",

        "Monstrous", "Parrot", "Doomed", "Reanimated", "The Chosen One", "Blastman" };

    public string[] tDescription = new string[236]
    {

        "+30% Performance, but always comes paired with Moody, Psychopath, Fussy, Geek or Vain.", "30% chance of becoming Stunned each turn.", "30% Performance if adjacent to a Crew Member, 60% Performance if alone.",
        "Will move to the nearest Crew Member. Every turn, there's a 2% chance that he eats an adjacent Crew Member, which will lose 1 Health per turn.", "If adjacent to more than 1 module for 10 turns, they lose their Profession and become Lunatic.",
        "If not in a Scientific Module or not adjacent to a Doctor for 10 turns, they lose their Profession and become Lunatic.", "Upon death, they explode and shit flies everywhere, making their Module and all adjacent Modules Excretion-flooded.",
        "60/50/40/30/20% Performance depending on the level of depth of the Dive.", "Once recruited, they gain a random Trait (except for Normal).",
        "35% Performance, but it increases by 2% for every enemy defeated, up to 20 enemies (max 75%). If you don't beat enemies or if you lose a battle, there's a 50% chance their Trait changes to Cannibal.",
        "30% chance of becoming Stunned each turn if in battle versus a Boss.",
        "At the start of each battle, they move to a random Module.", "If their Module is hit, gets Flooded or an adjacent module explodes, 50% chance of becoming Stunned for 3 turns.",
        "70% Performance, but when recruited they will automatically be placed in a random Module. Until adjacent to 4 Crew Members, other Crew Members will move close to them.",
        "Copies the most common Trait of adjacent Crew Members.", "20% Performance if adjacent to a Crew Member of the opposite Gender.",
        "After 20 turns of staying in the same Module, it will change to a Dumpster Module.", "20%P if alone, but it will increase to match the best-performing adjacent Crew Member.",
        "+20%P to adjacent crew members for 10 turns, after which exposed crew members will have -20%P.",
        "10% chance they quit the Dive after a battle.", "Every 2 turns, there’s a 20% chance their module sets on fire and a 5% chance it explodes.", "Every time they move, there's a 50% chance they lose 1 Health.",
        "40% Performance, increased to 50% if they have a Crew Member placed adjacent to the right (behind his back).",
        "Unless their module is Flooded, they and adjacent Crew Members have a 30% chance of becoming Sick.", "Will only have 3 Health.",
        "0% base performance, but +10% after every successful battle up to 6 times.", "Every turn, there's a 20% chance they swap places with a random Crew Member.",
        "At the start of each battle, their Performance will become either 70% or 20%.", "They will disappear at the start of battle, and reappear after 5 turns.",
        "They have a secondary Trait that changes randomly at the start of every battle.", "After every battle, there's a 20% chance they lose their profession and Senile is replaced by another random Trait.",
        "60% Performance in Offensive Modules, and 30% Performance in Defensive Modules.", "60% Performance in Defensive Modules, and 30% Performance in Offensive Modules.",
        "If you lose more than 500 Ship Health in a battle, they will quit the Dive.",
        "After every fight, there's a 20% chance you lose 100 coins.", "If you lose more than 500 Ship Health in a battle, -20% Performance to adjacent Crew Members for the rest of the battle.",
        "If they're not adjacent to an empty Module for 10 turns, they turn into a Lunatic. One adjacent empty Module will count as manned.",
        "A Scientific Module that they're in won't be operational. -20% Performance to adjacent Scientists.", "20% chance that treasure events turn out to be a battle instead.", "20% chance that a battle even turns out to be a rare treasure.",
        "If any adjacent Crew Member surpasses their Performance, they become Stunned for the rest of the battle.",
        "-20% Performance for 10 turns if a Crew Member of their same Profession is recruited.", 
        "30% Performance unless they're in the highest Module available in the Ship.", 
        "If your Ship is attacked, 50% chance their Module becomes Excrement-flooded.", "Each turn, there's a 30% chance they become Stunned  for 1 turn when adjacent to a Crew Member of the opposite Gender.", 
        "70% Performance in X Modules, and 30% in any other Module type. Their preferred Module type is only known when recruited.", 
        "Only exists as a hidden secondary Trait. Once per battle, if another Crew Member has 1 Health, they will be murdered and the Serial Killer Trait will activate. Nonetheless, you won't know who has Serial Killer as their hidden secondary Trait.", 
        "60% Performance, but -10% Performance to adjacent Crew Members.", "40% Performance, but +5% Performance to adjacent Crew Members.", 
        "Every turn, any adjacent Crew Member has a 30% chance of being Stunned for 1 turn.", "Copies the Ailment of adjacent Crew Members.", 
        "Once per battle, if adjacent to a Crew Member and after you lose 300 Ship Health, there's a 50% chance they both become Stunned for the rest of the battle.", 
        "-20% Performance versus small enemies, +20% Performance versus big enemies.", "20% chance of dropping dead after each battle.", "At the start of battle, there's a 50% chance they swap around 2 Modules.",
        "-20% Performance, but +20% Performance every time they lose HP", "Every time a Crew Member loses Health, they gain +10% Performance.", 
        "50% chance that after being recruited they divide into two Crew Members of Cadet Profession and 30% Performance.", 
        "If an enemy has tentacles, every turn there's a 20% chance they leave the Ship to embrace the enemy and die.", 
        "40% Performance, and if their Module is attacked, they swap with the nearest Crew Member right before the hit.", "Every battle, they won't have a Profession until 5 turns have passed.", 
        "After 20 turns, their clone will appear in a random Module, but they will have a random evil Trait instead. The clone will move until adjacent to their victim and then damage them for 1 Health per turn.", 
        "Likely that another 'In Love' applicant will appear. +10% Performance if adjacent to another In Love Crew Member. If an In Love Crew Member dies, the other will become Lunatic.", 
        "When recruited, they and a random Crew Member will change their Trait to In Love.", "After 20 turns following recruitment, they and a random Crew Member will both change their Trait to either In Love or Toxic Lover.", 
        "When recruited, a random Crew Member will change their Trait to Toxic Lover. Every turn, one Toxic Lover will gain 1 Health while the other loses 1 Health.", 
        "If an adjacent Crew Member loses Health, there's a 50% chance they sacrifice their own Health instead.", "20% of becoming Sick each turn.", "30% of making an adjacent Crew Member sick each turn.", 
        "Upon death, they explode and shit flies everywhere, making their Module and all adjacent Modules Excretion-flooded.", 
        "-20% Performance to the lowest-performing member in the Ship.", "When recruited, a random Crew Member is selected, adjacent to which the Friendzoned will have -20% Performance.", 
        "60% Performance, but -20% Performance to adjacent women.", "40% Performance, but 50% chance you gain 100 coins after each battle.", "If their module is attacked, there's a 30% chance it explodes.", 
        "If a Crew Member is about to die, they sacrifice their own life instead.", "Attracts the Hero Hideout Module. If you lose a battle, they sacrifice themselves to avoid the defeat.", 
        "In the Shop there's a chance that they swap places with a random applicant.", 
        "This Trait always appears in pairs in the Shop. They can only be recruited if both applicants are. +10% Performance when adjacent to each other.", 
        "20/30/40/50/60% Performance depending on the level of depth of the Dive.", 
        "After 30 turns, and if never below 2 Health, she creates a new Crew Member of Cadet Profession and Rookie Trait. If this Crew Member suffers Health damage, she will become Lunatic.", 
        "For the battle after they're recruited, all other Crew Members have a 50% chance of becoming Sick.", 
        "If their module is attacked, there's a 20% chance that it explodes. Every 10 turns, one Fart Bubble Module is formed in the vicinity.", 
        "Will try to dig a hole in their module out of habit, which will cause it to become Water-flooded after 5 turns.", "Upon death, they will revive with 30% Performance and Ghost Trait.", 
        "40% chance they puke at the start of a battle, becoming Sick and making their Module Excrement-flooded. After not puking twice in a row, they never puke again.", 
        "This Trait won't show during recruitment, instead they will show another random Trait. Once recruited, their Trait will change to Liar, will gain a random secondary Trait, and their Profession will change to another random one.", 
        "If their module is Water-flooded, they lose 1 Health every 2 turns.", "Every turn there's a 20% chance that their and any adjacent Modules all become Excrement-flooded.", 
        "20% chance that if a Crew Member dies, they are revived with 40% Performance and the Reanimated Trait.", "If they are in an Offensive or Defensive Module, every turn there's a 10% chance they become Lunatic.", 
        "Adjacent Doctors will have -20% Performance.",
        "Shows another fake trait in shop. After 2 battles, at the start of each battle there’s a 20% chance Traitor is revealed and they proceed to sabotage the Dive dealing 1dmg/4turn to random adjacent crew members.",
        "Shows another fake trait in shop. 15 turns after recruitment, the Undercover Competitor trait will activate, and everything in the Shop will cost 50 coins more. You still won’t know who has Undercover Competitor as their hidden secondary Trait.", 
        "At the start of battle, they swap into another Module of the same type as the one they're in.", "-20% Performance for as long as you have an Excrement-flooded Module.", 
        "If there's an Excrement-flooded Module, they will swap places with this Module, clean it up, and gain 1 Health.", 
        "Will create a 30% Performance clone of himself without a Trait in an adjacent Module, but if this Module becomes Flooded the clone will die.",
        "60% base performance. +20% performance in automatised/unmanned modules. +30% performance cap. If its Module becomes Flooded it will short-circuit and die. Cannot be healed.", 
        "If placed adjacent to the Captain, they will reveal who is a Serial Killer or Undercover Competitor, as well as who is a Liar, Traitor or Cheeky Undergrad in the Shop.", 
        "0% Performance if in or adjacent to an automatised Module.", "After every battle, there's a 20% chance his Module is destroyed and they are returned to the bench, and a 80% chance they change it to another random Module.", 
        "If their Module is Water-flooded, every 2 turns they will swap places with other Water-flooded modules.", 
        "This Trait won't show during recruitment, instead they will show another random Trait. Once recruited, their Trait will change to Cheeky Undergrad and their Profession will change to Cadet.", 
        "In the next battle after a victorious Boss battle, those that were adjacent to them will become Sleepy.", 
        "60% Performance if they are a Doctor, Scientist or Biologist. If they're not, their Trait will change to Jealous whenever a Doctor, Scientist or Biologist is recruited.", 
        "+10% Performance to the Crew Member adjacent to the left.", "After 10-40 turns they will go blind and gain the Trait 'Bad Eyesight'.", 
        "5 turns after a battle starts, there's a 50% chance the enemy turns out to be a different kind of enemy.", "Will be Sick for as long as they're not in the furthest-from-enemy Module in the Ship.", 
        "At the start of battle, there's a 70% chance they becomes afflicted with 1 Ailment at random except for Lunatic.", 
        "If their module explodes, they escape to the nearest empty module or to the bench right before the explosion.", "At the start of battle, there's a 50% chance they talk a small enemy creature into not attacking.", 
        "They will move to the nearest Module in the direction of the Captain. Once adjacent to the Captain, their Trait changes permanently to Boss Wannabe, and they cannot be moved from that Module.", 
        "Adjacent Scientific Modules won't have any effect.", "Their Profession changes randomly at the start of battle.", 
        "If they become Asleep, they snore heavily, waking up any other Asleep Crew Members, but adjacent Crew Members -10% Performance", 
        "Has 5 Health, but always comes paired with Vain, Competitive, Low Self-esteem, Bully, Ex-prisoner or Thick.", 
        "If they're missing Health, once per battle they will heal 1 Health by draining it from the nearest Crew Member.", 
        "Can't die. Every 2 turns, there's a 50% chance they disappear for 5 turns.", "Has 5 health, but 30% Performance.", 
        "At the end of each battle, if they lost Health, you lose 50 coins. If they died, you lose 100 coins.", "They will quit if there's another Crew Member with the Cadet Profession or Rookie Trait.", 
        "30% performance, but if the module he's in becomes Water-flooded, heals to full Health and gains +40% Performance.", "70% chance of dropping dead after each battle.", "Just a normal person for once. No effect.", 
        "If their Module is hit by a physical attack, they will open the door and drown.", "Once placed in their Module, they get stuck and can't be moved to a different Module.", 
        "If your Ship is attacked, 50% chance their Module becomes Water-flooded.", 
        "If a Module becomes Water-flooded, they will fix it. 5 turns later, there's a 50% chance the plumbing collapses and the Module becomes Excrement-flooded.", 
        "If their module is Water-flooded or Excrement-flooded, they become Lunatic.", "Will heal 1 Health after defeating an enemy creature, but has also a 30% chance of starting the next battle Sick.", 
        "Once you place them in a Module, they can only be moved to Modules of the same type.", "If their module is attacked, their Trait will change to Lunatic until the end of the battle.", 
        "-20% Performance if an adjacent module is attacked, Flooded or explodes.", 
        "They will move closer to the nearest Organic Module. When adjacent to one, they will eat it, and the Crew Member inside will either relocate to an empty Module or die.", 
        "Every turn there's a 10% chance he becomes Sick.", "Every 10 turns they cough and lose 1 Health. Every 10 turns, one Fart Bubble Module is formed in the vicinity.", 
        "Any Module that they're in becomes infested with bedbugs. Any Crew Member in that module for 15 turns in a row becomes Lunatic.", "30/50/70% Performance at 90/50/30% Ship Health.", 
        "For every 2 Crew Members that die, they will build 1 Bone Capsule.", "For every Crew Member that dies, they heal 1 Health and give you 100 coins. If the corpse was of a Businessman, they give you 200 coins.",
        "If their module explodes, they survive and unleash newfound power changing their Trait to Blastman.", 
        "If they die, they return in the next battle after 5 turns with their trait changed to Monstrous.", "If a battle takes more than 8 turns, they will become Sleepy.",
        "+5% performance for every different item they’ve ever held.", "If your Ship is not top-bottom symmetrical, -20% Performance and after 10 turns will become Lunatic.", 
        "Their aim is to kill the General Officer. Will swap places to be adjacent to the General Officer, and then do 1 Health damage every 2 turns.", 
        "If they're not placed in the lowest possible level of the Module layout, -20% Performance and after 10 turns will become Lunatic.", 
        "At the start of a battle, 40% chance of abducting themselves together with an adjacent Crew Member, and after 1 battle passes, only said crew member will return, with this Trait changed to Has Amnesia.", 
        "-20% Performance in Scientific Modules, +10% Performance in Organic and Normal Modules.", 
        "After every battle, there's an increase in 20% chance that their trait changes to Caveman, starting from 0% after the first battle.", 
        "The crew members that were adjacent to them in the previous battle, will become Sleepy at the beginning of the next battle.", 
        "If they're attacked by a Monstrous crew member, he will eat them. They will also eat enemy parasites or babies that invade the Ship, and not be affected by them.", 
        "Ignore the requirements of the Module he's in. However, any Module that he was in will explode after 20 turns.", 
        "After every battle, any adjacent members will have a 50% chance of gaining the Glutton trait.", 
        "After every battle, any adjacent members will have a 50% chance of gaining the Drunkard trait.", 
        "If a Scientific Module is hit by the enemy, they will heal the Ship Health damage back up, however whenever they do so there's a 40% chance they die electrocuted.", 
        "Centenarians and Supercentenarians will only have a 10% chance of dropping dead after a battle if adjacent to the Caregiver. Each adjacent Crew Member has a 20% chance of avoiding an Ailment if they are to be afflicted by one.", 
        "If in the last battle a Crew Member died or a Module exploded, there's a 50% chance you get 100 coins.", 
        "If their Module or any adjacent one is Water-flooded, they will immediately quit the Dive. If you encounter a Shipwreck, it will yield better loot.", 
        "If a Crew Member died in the previous battle, all Crew Member effects other than Stacking Bonuses will be deactivated for the first 5 turns.", 
        "If a Crew Member dies, there's a 40% chance they return after the battle without a Profession and with the Thick Trait.", 
        "After each battle, there's a 50% chance they take 100 coins from you. They don't do anything useful. If they die, you get 80% of the coins they took back.", 
        "If a Crew Member dies, under no circumstance will they return in any shape or form, and will instead rest in peace.", 
        "Their Module will count as 4 modules when it comes to enemy targeting. It will always Water-flood first. If their Module is hit, there's a 25% chance it explodes. If they die, they will return after 1 battle without them.", 
        "Every turn, there's a 20% chance they lose 1 Health. If their module is attacked or is Water-flooded, their trait will be changed to Normal, and the closest Crew Member will have the Possessed Trait added to them.", 
        "Every turn they lose 1 Health, then gain 1 Health, then lose 1 Health, and so on.", "At the start of battle, there will be a 50% chance they don't have their Profession.", 
        "If a Boss drops below 50% HP, there's a 50% chance they heal the Boss for 200 HP.", "The first Module that they're placed in will turn into a Bunker Module. They can't move to other Modules.", 
        "25% chance of becoming Sleepy every 2 turns.", 
        "You can activate Karen to have a 50% chance of rerolling the contents of the Shop. After rerolling the Shop 3 times this way, Karen gets tired and their Trait will change to Argumentative.", 
        "If you have 1 of each type of Module, +40% Performance.", "If you don't recruit this applicant, they will show up very frequently in the Shop (on average showing once every 2 Shops).", 
        "If placed adjacent to another Crew Member, every 8 turns they will be attacked by said Crew Member and lose 1 Health, but this will increase the BDSM Enthusiast's Performance by 20% each time, and it resets for the next battle.", 
        "60% Performance in Normal modules, 30% Performance in the rest.", "If adjacent to a Cadet for 15 turns, the Cadet will copy their Profession.", "If a Module explodes, +15% Performance.", 
        "Can't be placed in any Module that doesn't cost at least 300 coins, but if their Module was undisturbed, they will pay a rent of 50 coins after every battle.", 
        "-20% Performance unless their Module is adjacent  to the Captain. Unless they die, they will be likely to show up in future Dives (on average showing once every 4 Shops).", 
        "At the start of each battle, there's a 30% chance that if adjacent to a Crew Member, said Crew Member will become Stunned until you pay 100 coins.",
        "If disturbed by an adjacent module, -1 HP to the crew member in the module the disturbance came from. If undisturbed for a battle, produces the item Ship in a bottle.", 
        "Only applies to men. If a woman is in the Ship, no matter how far, she will gain the Pregnant Trait after 15 turns.", 
        "Each Shop event, you can sell back 1 Module in your bench for half its original coin value.",
        "20% Performance to the Crew Member below their Module, but will also prevent them from becoming Sleepy or Asleep.", "Operates and performs normally even if their Module is Frozen",
        "Any crew member adjacent to them for 30 turns will become permanently Sick.",
        "If an adjacent crew member is damaged by an enemy, they deal 50 damage to that enemy.",
        "Only has 2 base HP, however if attacked, there’s a 33% chance the enemy misses.",
        "If an adjacent crew member has 2 or less HP, 50% chance they fully heal, and 50% chance they lose 1 HP and become Sick.",
        "Won’t suffer damage from an enemy attack more than once per battle.",
        "If they hold an item, 33% chance that it breaks after a battle.",
        "-20% Performance if they hold an item.",
        "Once they receive an item, it cannot be swapped by any means.",
        "At the start of battle, they will gift their item to a random adjacent crew member.",
        "If adjacent to a crew member with an item, every turn there’s a 5% chance this trait actives, with a 50% chance that item is destroyed, and a 50% chance it’s stolen.",
        "If they wake up from being Asleep, they will disappear.",
        "If an adjacent crew member dies, -10% performance permanently.",
        "If Asleep, every 2 turns moves to an adjacent module.",
        "If Asleep, +1 HP every 4 turns.",
        "If Asleep, -1 HP every 4 turns.",
        "Their performance gains and losses are reversed.",
        "At the end of battle, 50% chance you lose 100 coins and 50% chance you gain 100 coins. At the end of combat they will gamble with your money.",
        "+20% performance in a Wild module, and can be moved in and out of it.",
        "50% chance at the start of battle that they leave their item behind on the bench.",
        "+1 HP per 4 turns if in a Wild module.",
        "25% chance for each adjacent module to be set on fire at the start of each battle.",
        "Every 10 turns, there’s a 10% chance their module becomes Damaged.",
        "Always comes with the item Lucky Baby equipped. If they lose hold of this item, they become Lunatic.",
        "+40% performance in a Damaged module.",
        "After 6 turns, 50% chance they repair a Damaged module, and 50% chance they turn it into an Unstable module.",
        "Every 4 turns, there’s a 20% chance their module becomes Detached.",
        "-10% performance, +50% performance if their module is Detached.",
        "If their module is set on fire, produce 1 Tasty Pizza.",
        "If they and 4 adjacent crew members all have the same performance, +20% performance to everyone.",
        "If they or any adjacent module is hit, their module will become detached.",
        "-10% performance, but +80% performance if they’re in an unstable module.",
        "Their module will be inactive.",
        "Their module will become Wild at the end of the battle.",
        "-1HP/4turns in a Wild module.",
        "If in or adjacent to a Wild module, produce 1 Wooden Puppet at the end of battle",
        "If an adjacent module is set on fire, they will put out the fire after 2 turns, and there’s a 10% chance they die in the process.",
        "If an adjacent module is water-flooded, they will rescue the crew member and send them to the bench.",
        "Their module thaws from frozen after 2 turns.",
        "If their module is frozen, they are immune to it and +20% performance.",
        "+20% performance, but every 8 turns, there’s a 15% chance their module becomes damaged.",
        "-10% performance, but if their module is inactive, +20% performance instead.",
        "At the end of battle, will send any adjacent crew members in wild modules to the bench.",
        "Every 4 turns, moves to an adjacent module they haven’t been in this battle yet.",
        "+20 Performance. Every turn, they have a 10% chance of attacking the closest Crew Member for 1 Health damage, unless they’re also Monstrous.",
        "Will copy the Profession of an adjacent Crew Member and also apply Stacking Bonus.",
        "Performance is halved and will inevitably die after 15 turns.",
        "Their skin will be grey and cracked. Their Performance will slowly decrease at a rate of -1% per turn.",
        "They will have 10 Health, 100% Performance and are immune to explosions, but if they die you lose the Dive",
        "They rescue from death and send to the bench up to 4 crew members, after which they quit the Dive to help in other places."

    };
    public string[] profDescription = new string[] { "Each architect has an extra free slot in any adjacent space. \n 4x = After each battle, you can reroll the requirement of one module. \n 8x = You can move around your placed slots freely. \n 12x = If you have more than 24 modules in your ship, it becomes a mega structure that deflects 20% of attacks.",
        "After being adjacent to a crew member during a battle, you can reroll their trait. 20T CD. \n 3x = When you reroll someone's trait, choose one from a random selection of 3. \n 6x = Can add a random Erudite Trait as secondary traits to crew members",
        "Once per Biologist, after participating in a victorious monster battle, can build a Basic Fishcapsule. \n 4x = once per biologist, can build an exclusive organic module depending on the defeated sea creature. \n 8x = Can build organic mega-modules from abysmal bosses shown in the Logbook.",
        "Once per Developer, after being in a module during a battle, can automatise that module. \n 3x = Increase module recharge speeds by 25%. \n 6x = Increase module recharge speeds by 40%, and if a crew member dies, they will be replaced by a copy of them with the Robot trait.",
        "Once per Engineer, after being in a module during a battle, can rebuild it into another random module. \n 3x When rebuilding a module choose 1 of a random selection of 3. \n 6x = can fuse two modules to get a random mega-module of the same type as the fused modules.",
        "No special effects, but cheap. \n 4x + GO = Cadets will count as GO for module requirements. \n 8x + GO = If the GO dies, upgrade one Cadet to be the new GO.",
        "Once per battle, can heal an adjacent crew member by 1HP. \n 3x = Will also cure the ailment of an adjacent crew member once per battle. \n 6x = Each Doctor can attempt to reanimate a crew member that's died, with a: 20% chance +Doomed, 60% chance +Reanimated, 20% chance of returning in a perfect state.",
        "Once per Recruiter, they can be paid 150 currency to recruit one random crew member guaranteed to be of a profession you already have. \n 2x = Once per Shop, you can reroll the shop by paying 200 currency. \n 4x = You can fire crew members and get some money back.",
        "Increases the chance of a module or applicant having a whopping discount. The more businessmen, the higher the chance and maximum size of discount. \n 3x = During Shop, you can invest a minimum of 500 currency and get it back with +20% interest during the next Shop phase. \n 6x = You can enter debt to buy in Shop,m in exchange of interest.",
        "Each scientist, when adjacent to a Scientific module with a crew member, can subject them to Radical Testing. After 10 turns: 10% chance +Lunatic, 40% chance +Doomed, 50% chance he becomes Augmented, fully healing and gaining +1 max HP. \n 3x = Enhance the body (+1 max HP) or the mind (+25% performance cap) of an Augmented crew member. \n 6x = Grant an Augmented crew member a random Super Trait.",
        "Can foresee the type of content of nearby nodes. \n 4x = Unlock new routes and nodes that you previously couldn't see, which may include exclusive events with unique rewards, such as exclusive modules, crew members and objects like fossil.",
        "Unlocks extra power in certain modules. \n 4 Cadets + GO = Cadets will count as GO for moudle requirements. \n 8 Cadets + GO = If the GO dies, upgrade one Cadet to be the new GO.",
        "Once per Inventor, at the end of each battle create 1 item.",
        "Instead of normal autos, Wizards cast magic beams that deal x1.3 damage."};
    public int[] traitPrice = new int[236] { 2, 0, 1, 0, 1, 1, 1, 1, 1, 2,
                                              1, 0, 0, 0, 2, 1, 0, 2, 1, 0,
                                              0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
                                              0, 2, 2, 0, 0, 0, 2, 0, 0, 2,
                                              1, 0, 1, 0, 1, 0, 0, 1 , 1, 1,
                                              0, 1, 1, 0, 0, 1, 2, 1, 0, 0,
                                              1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
                                              0, 1, 1, 2, 0, 2, 2, 1, 2, 1,
                                              1, 1, 0, 1, 2, 1, 1, 0, 0, 2,
                                              1, 0, 1, 1, 0, 1, 2, 2, 1, 1,
                                              1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                              0, 2, 2, 0, 0, 1, 1, 1, 1, 1,
                                              1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
                                              1, 2, 1, 1, 1, 1, 0, 1, 1, 1,
                                              2, 2, 2, 1, 0, 1, 1, 0, 1, 1,
                                              1, 1, 1, 2, 1, 2, 1, 1, 1, 2,
                                              0, 0, 2, 0, 1, 1, 1, 1, 1, 0,
                                              1, 1, 2, 2, 1, 1, 1, 2, 2, 2,
                                              0, 0, 1, 2, 2, 1, 2, 0, 2, 1,
                                              0, 2, 0, 0, 1, 1, 1, 0, 1, 1,
                                              2, 1, 2, 1, 2, 1, 2, 0, 0, 1,
                                              2, 1, 1, 0, 1, 2, 0, 0, 0, 1,
                                              1, 2, 2, 1, 2, 2, 1, 1, 2, 1,
                                              0, 0, 0, 0, 0, 0};
    public int[] profPrice = new int[] { 5, 5, 6, 5, 5, 4, 5, 8, 5, 5, 8, 8, 5, 6 };

}