using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "ModInfo", menuName = "My Game/Mod Info")]
public class ModInfo : ScriptableObject
{
    public string[] names = new string[235] { "Torpedo Launcher", "Exhausting Super-Cockpit", "Excrelaser", "Whale Corpse Explosion", "Blood Beam", "Seaweed Barrier", "Corpse-Utilising Module", "Cult Headquarters", "Portable Nursing Home", "Performance Extractor",
        "Improperly Installed Mega-Rocket", "Ammonite Capsule", "Age-reversing Treatment", "Dream Extractor", "Triumphant Regenerator", "Jelly Flexi-Membrane", "General Officer AI", "Adjacent Automatisation", "Mind Control Unit", "Motherly Jellycarer",
        "Impact Redirector", "Chamber of Sacrifice", "Mimic", "Excretor", "Golem", "Videogame Weapon Materialiser", "Mini-Hospital", "Passive Regenerator", "Shock gun", "Robot Factory", "Hacking Peripheral", "Harpoon Dispenser", "Doping Clinic",
        "Anglerfish Glare", "Commander's Cockpit", "Stingray Fin", "Urchin Megacarapace", "Laser Beam", "Magicoral", "Quantum Predictor", "Waste Extractor", "Electroconvulsive Capsule", "Recycling Unit",
        "Biotransformer", "Bunker", "Ritual chamber", "Casino", "Unlicensed Weed Garden", "Health Accumulator", "Buffet Restaurant", "Military School", "Module Repair Kit", "Chemistry Store", "Gym", "Defensive Synergiser", "Acid Sprayer",
        "Divine Immunity", "Impact buffer", "Self-Destruct Module", "Excreshield", "Net Gun", "Explosive Redirector", "Coin Bullet Gun", "Oxygen Rockets", "Flamethrower", "Sticky Seaworm", "Combo Bomb", "Combo Regenerator", "Mental Reversal Capsule",
        "Corpse Recycler", "Eject Button Module", "Plumbing System", "Pain-Sharing Compartments", "Pain-Splitting Compartments", "Vital Oxygenator", "Beast Taunter", "Mistery Room", "Scrap Robot Factory", "Magical Storage Room", "Relaxing Mini-Spa",
        "Mini-Nuke Dispenser", "Irresistible Bait Launcher", "Perfect Balance", "Chronic Beam", "Defensive Perfection", "Offensive Perfection", "Beautiful Fish Tank", "Decompression Core", "Oxygen Extractor", "Healthy Gatler",
        "Brain Giga-Aumentator", "Portable Mini-University", "Interdimensional Mega-Training", "Portable Bank", "Excellent Bombardier", "Vibrating Blaster", "Blood Absorber", "The Golden Chamber", "Hero Hideout", "Sadomasochism Dungeon",
        "Electric Shockwave", "Gunfire Inverter", "Lunatic Brutaliser", "Fossil Reviver", "Cursed Coffin", "Magical Swap Boxes", "Military Waking Alarm", "Dumpster", "Wasteful Fuel Producer", "Trash Compactor", "Selfish Protection Capsule",
        "Kinetic Absorber", "Discharge Sponge", "Isotopic Barrier", "Monster Drainer", "Health Weaponiser", "Danger Alert", "Mind Reader", "Laser of Death", "Restructurator", "Basic Fishcapsule", "Business Centre", "Megaton Core",
        "Sticky node", "Tentacollector", "Chef Academy", "Explosive Charger", "Pain Transformer", "Cotagion Beam", "Water-Based Doping Module", "Arctic Hull", "Chamber of Infinite Wisdom", "Resourceful Blocker", "Systemic Freezer",
        "Gambletron 3000", "Frozen Node", "Seafood Absorber", "Recrutibot 3000", "Item Transformer", "Steamthrower", "Marine Hostage", "Co-pilot's Cockpit", "General Quarters", "Autopilot Navigator", "Kidnaptron 3000", "Professional Union",
        "Corruption Node", "Grand Professional Abduction", "Desperate Disintegrator", "Greed Pact", "Mirror Room", "Ineptitude Distiller", "Gleaming Ruby", "Sanatorium of Chaos", "Campus of Chaos", "Alien Takeover",
        "Gates of the Chosen One", "Portable Wormhole", "Gleaming Sapphier", "Teleportation Laboratory", "Purge House", "Profession Replicator",
        "Eject Button Capsule",
        "Sleepy Sponge",
        "Spike Chamber",
        "Jacuzzi Module",
        "Seafood Producer",
        "Crocodile Tank",
        "Insane Augmentator",
        "Item Bombardier",
        "Item Deflector",
        "Item Recycler",
        "Bedrock disintegrator",
        "Row Channeler",
        "Unstable Channeler",
        "Electrifier",
        "Magifish Spawn",
        "Sea Urchin Spawn",
        "Uncontrolled Greenhouse",
        "Fire Station",
        "Heat Beam",
        "Volcanic Container",
        "Sushi Kitchen",
        "Brick Oven",
        "Forge",
        "Escape Pod",
        "Isolator",
        "Ephemeral Booster",
        "Satellite Bombardier",
        "Petrifying Defender",
        "Sperm Bank",
        "Mega Chimney",
        "Freezeitor 2000",
        "Missile Deflector",
        "Rooted Core",
        "Uncomfortable Cabin",
        "Unstable Gatling Gun",
        "Overheat Laser",
        "Reckless Sparker",
        "High-precision Cutter",
        "System Cooler",
        "Confinement Room",
        "Gravity Engine",
        "Anti-gravity Blaster",
        "Contained Power Beam",
        "Biomass Power Station",
        "Oil Platform",
        "Paper Factory",
        "Hunting Settlement",
        "Prehistoric Shelter",
        "Disaster Laboratory",
        "Irritable Volcano",
        "Jungle Ruins",
        "Prehistoric Portal",
        "Crummy Torpedo Launcher",
        "Crummy Deflector",
        "Abandoned Laboratory",
        "Latent Mega Iceberg",
        "Glacier Producer",
        "Sewer",
        "Atlantis Portal",
        "Human Catapult",
        "Sushi Bar",
        "Mediocre Clinic",
        "Element Changer",
        "Fart Bubble",
        "Tobacco Bubble",
        "Frozen Coffin",
        "Eye of the Calamity",
        "Pearlcore",
        "Millennial Explorer",
        "Morgan’s Submarine",
        "Selfless Whale",
        "Nuclear Fusion Energiser",
        "Nuclear Fission Disintegrator",
};

    public string[] moduleDetails = new string[235] {"+20 attack. Has a 50% chance of dealing damage to 2 enemies at once.",
        "+40 attack for as long as the crew member in it has 4 or more HP.",
        "Extracts any Excrement from this/adjacent modules and turns it into extra +50 dmg that has a slight chance of inflicting Poison status.However, if this module gets hit, it will explode and throw Excrement into all adjacent modules.",
        "Explosion that does 500 dmg to all enemies. Built from the item Bulging Whale Corpse.",
        "For every 1 Health a Crew Member loses, +10 dmg for the rest of the battle",
        "Ship HP will be immune to attacks of lower than 40 dmg.",
        "Whenever a crew member dies in battle, his corpse will be launched to block an incoming attack.",
        "Any crew member adjacent to this module will follow the same fate as the crew member inside it, whether it is an Ailment or death.",
        "Will generate an extra crew member with no profession and with the Supercentenarian attitude in any adjacent capsule.",
        "Increase performance of the Crew Member in it to 100%, but there’s a 20% they die after each battle.",
        "Huge rocket that deals 300 damage.However, it doesn’t fire normally, instead, it only fires right after the module has been hit by an enemy attack.",
        "Befriends certain sea creatures, which will no longer attack you.",
        "Turns a crew member into a Cadet with Rookie Trait. Charges up after 3 battles.",
        "If the crew member in this module is Asleep, cover the ship in a shield of clouds that adds 300HP to your ship.",
        "If you won a battle without any module exploding, heal 100 Ship Health",
        "Once per battle, bounce 1 enemy attack back to the enemy.",
        "AI that simulates the expertise of a General Officer being in an adjacent module.",
        "Automatises an adjacent module.",
        "If adjacent to a scientific module, it can work unmanned. Mind controls an adjacent crew member to behave like another adjacent crew member.",
        "If this module or adjacent ones were attacked during a battle, heal the ship +100HP at the end of the battle.",
        "Once per battle, you can sacrifice and explode an adjacent module instead of taking ship dmg.",
        "A crew member in or adjacent to this module may be sacrificed at random instead of taking ship dmg.",
        "Copies the functionality of an adjacent module.",
        "Oozes monsters dregs that inflict Sick status.",
        "Works unmanned. Will absorb the first two enemy hits, preventing any ship dmg, after which it will be destroyed.",
        "Converts advanced videogame weapons into real ones that will inflict +50dmg.Every turn it has a 40% chance of failing. Can only be used by Cadets, but those that are in this module for more than 1 battle start suffering from decreased performance.",
        "Once per battle, heal +1HP to 3 crew members that are in/adjacent.Must be manned by a Doctor.",
        "Every 10 turns, heals 100 Ship Health",
        "Inflicts Paralysis status.",
        "Once per battle, generates an extra crew member that will last only for one battle, with no particular profession and with the attitude Robot, and can be placed in any adjacent capsule.Flooding will disable this module’s effect.",
        "Makes an adjacent module obviate its requirements of activation.",
        "+60 dmg every 3 attacks.",
        "If a crew member stays in this module for 2 turns, his/her performance will increase for the rest of the battle.",
        "Stuns an enemy for two turns",
        "If manned by a General Officer, +30dmg (+60dmg against shell).",
        "You have the first turn every battle.",
        "If the enemy hits this module with a physical contact attack, he will lose 150HP.If this happens 2 times, the enemy will be inflicted Poison status.The beauty of the carapace will trigger the enemy to attack it more frequently.",
        "Charges up for 4 turns, then, it will then shoot a 300 dmg laser beam that penetrates through all targets. If the module is disturbed, it will reset the charge bar.",
        "If you finished a battle without this module being disturbed, shield your Ship for 100 Ship Health.",
        "Might predict certain outcomes of %-based effects, like pregnancy, lovers becoming toxic, enemy freezing, etc.",
        "Extracts any Excrement from this and adjacent modules, preventing their effects.",
        "Fixes Lunatics, giving them a positive/neutral attitude instead.However, there’s a 20% chance they won’t survive the process and die. Takes 1 battle to fully charge.",
        "Turns dead enemies into O2 and some currency.",
        "Can turn several dead enemies into an organic module.Takes 3 battles to fully charge. ",
        "Every fight it takes 5 turns to charge up, then, it becomes indestructible and crew takes 0 dmg in it.",
        "Will summon 2 or 3 crew members of Ghost trait and no profession that will disappear after the battle.",
        "Slightly increases positive odds and decreases positive odds of adjacent events.",
        "Will turn any attitude into Stoned if a crew member stays in it for 2 battles, but only while they’re in the module.",
        "For every defensive module in the ship, including this one, you get 30 ship HP. Stacking caps at 8.",
        "Will turn any attitude into Glutton if a crew member stays for 2 or more turns inside this module.",
        "Adds 20 dmg to the ship’s base attack, and will convert any crew member’s profession into Cadet if stayed inside this module for one battle",
        "Once per battle, will repair the first adjacent module that becomes damaged or unstable.",
        "This module will act as a professional Doctor if a crew member mans it for 2 battles in a row.",
        "Will turn any attitude into Bodybuilder if a crew member mans it for 2 battles in a row.",
        "Has a 33% chance of freezing an enemy whenever an adjacent defensive module activates.If operated by a General Officer, the chance is increased to 50%.",
        "Sprays an acid at the start of battle that will remove the enemy shell after 2 turns.",
        "Activate this module once to make it and its crew member immune to everything for one turn.",
        "If an attack hits this module, it does 0 dmg to the ship. If operated by a General Officer, it also deals 100 dmg to the enemy.",
        "Activate this module for it to separate from the ship, and launch itself with its brave crew member into the enemy, causing a 500 dmg explosion. If operated by a General Officer, it deals 800 damage instead.",
        "Once per battle, transforms any shit, vomit, piss or farts in it or in any adjacent modules into a gross shield that blocks one enemy attack. If this module is hit however, those substances will leak into all adjacent modules.",
        "Does a mere 50 damage.If used at the very end of a battle to end it, the creature is captured instead, which will spare you from corpse-exploding effects and yield items.",
        "If an adjacent module is gonna explode, instead, redirect the explosion into the enemy, dealing 300 dmg.",
        "Compresses your saved currency into hard golden bullets that deal great damage. For every 100 coins spent, deal 200 damage.",
        "Pack your precious O2 into rockets that explode to deal 200 dmg.",
        "If used 3 times in a row against the same enemy, will inflict Burn status. If set on fire, +30 dmg.",
        "Can be manned. Sticks to adjacent modules forever. Crew members inside this module are immune to Ailments.",
        "If you activate 3 effects in or under 3 successive turns, launch a Combo Bomb that does 300 dmg.",
        "If you activate 3 effects in or under 3 successive turns, heal for 100 Ship Health.",
        "Inverts the performance of the crew member in it.",
        "Recycles corpses of dead crew members into useful O2.",
        "Use this module to eject the whole ship away from a battle. After this, the module is destroyed.There is only one Eject button module in each Dive.",
        "Extracts any Excrement from anywhere in the ship. However, if this module gets hit, these substances will leak into every module of the ship.",
        "They always appear as a pair in the shop, for 100 each. Whenever a crew member takes damage in one of the modules, so will the other one.",
        "They always appear as a pair in the shop, for 100 each. Whenever a crew member takes damage in one of the modules, you can choose the other crew member to receive the damage instead.",
        "Transform 1 O2 into healing 1 HP to any adjacent crew member.",
        "Taunts the enemy to heavily increase the odds of the enemy attacking adjacent modules.",
        "Every battle, this module turns into another random module that isn’t a Mega-Module.",
        "Only once per battle, repurpose any module into a no-profession crew member with Robot Trait. You can even repurpose a module that has just been destroyed.Flooding will disable this module’s effect.",
        "Only once, you can place an item in this module, and after 20 turns, it will return back as a different item.",
        "If a crew member spends 1 battle undisturbed in this module, they will fully heal at the end of the battle.",
        "Devastating attack that can only be used once per battle and inflicts 300 dmg to all enemies. Requires the item Mini-Nuke.",
        "Launches bait far away to lure a monster away from the battle and escape. However, the monster will eat the bait and will be guaranteed to come back much stronger in future map nodes.Breaks after use.",
        "Equalise the enemy's HP with the ship’s HP, calculating the mean of both values and applying it to the enemy and the ship. After use, it’s destroyed. There’s only one available per Dive.",
        "Once per battle, shoot a beam at the enemy that does 200 dmg for every Ailment the enemy has.",
        "If manned by a General Officer, the enemy cannot harm your ship’s HP unless it first lands a hit onto this or any of its adjacent modules.",
        "If manned by a General Officer, the enemy will receive +100 dmg unless it first lands a hit onto this or any of its adjacent modules.",
        "Unmanned. This module is permanently water-flooded. Every 2 turns, a random Biologist from your crew will move 1 step closer to this module until he’s adjacent to it, even if it means swapping places with others.",
        "This and adjacent modules can't explode",
        "If this module gets flooded, it produces 1 O2 this battle.",
        "If your Ship Health is at least 90% full, +40 dmg.",
        "After 12 turns, any crew member inside this module will change their Trait to Genius.If the module is disturbed, it will reset the charge bar.",
        "After 15 turns, any crew member inside this module will change their profession to another profession of your choice. Takes another 15 turns to recharge. If the module is disturbed, it will reset the charge bar.",
        "This module, after placing a crew member in it, closes its doors and transports the crew member into another dimension for 3 battles, during which it cannot be used. Then, he returns transformed into a improved being with two positive traits, higher HP and base performance.There is a 25% chance the crew member returns as a monstrous abomination that shits himself.",
        "Put a maximum of 1000 currency into this module (capped). If it was undisturbed during a battle, it produces extra currency equal to 40% of the amount placed. But if the module was disturbed, you lose all the currency placed.",
        "An excellent +50 dmg with no drawbacks. However, the toilet in it is broken, so it gets full of shit after 4 turns.If it’s hit by an enemy, shit spreads to any adjacent modules.",
        "+50 dmg. However the module vibrates while operational, which means every 4 turns, there’s a 50% chance an adjacent module becomes damaged.",
        "If your crew has taken 6 HP damage this battle, heal +200 Ship HP",
        "Costs 5000 coins and comes more easily to players with lots of coins. Offers maximum comfort to the crew member in it, however it is extremely delicate as it is beautiful. If undisturbed for 30 turns, it magically transforms into any desired module in the game, and will make its crew member a Posh Millionaire Businessman of 160% performance.",
        "Attracts applicants with the Hero Mindset trait. If manned by a crew member with the Hero Mindset trait, he will have 100% performance and if attacked, will hit the enemy back for 100 dmg. Only one per Dive.",
        "If a crew member takes damage in this module, his attitude changes to Masochist.",
        "+50 attack, but has a 50% chance of damaging the ship.If operated by a General Officer, there’s a 0 chance it damages the ship.",
        "The lower your Ship Performance, the higher the added damage. From +0 dmg at 100% Ship Performance to +70 dmg at 5% Ship Performance.",
        "If a monster hits a module with a Lunatic in it, he will receive 200 dmg.",
        "If you have a fossil, it can transform it into a random biologist-exclusive organic module.",
        "Any crew member in it will have terrible luck.",
        "They always appear as a pair in the shop, for 100 each. At any time, even before an imminent attack, but only up to twice per battle, swap around the crew members that are in these boxes.",
        "Unfreezes and wakes up asleep crew members.If operated by a General Officer, a massive performance boost follows these effects.",
        "Doesn’t have any particular effect.",
        "Charges up your modules 15% faster than normally, and produces some O2 as a byproduct. Choose an adjacent module that will become a Dumpster for this module.This module produces a lot of waste and needs a place to dump it in.",
        "Empty all the junk from an adjacent Dumpster, returning it to its original state (if it didn’t have one, it gets one randomly), compress the junk and turn it into either a huge scrap missile that deals 300 dmg, or a shield that blocks 200 dmg.",
        "If this module is about to get hit, instead, he grabs the crew member inside it and uses them to block the hit, they die but your ship suffers no damage.",
        "Absorbs any type of movement of crew members in the ship. Any time 1 crew member moves, Kinetic absorber charges up 50%. After charging up to 100%, it fires a kinetic blast to the enemy that deals 300 dmg.",
        "Sponge capsule that secretes calming spores, which stop the enemies from going berserk.",
        "Once per battle, activate to heal your ship’s HP for the same amount of damage you would have taken from the incoming enemy attack.",
        "Your ship heals for 10% of the dmg you deal to the enemy in every battle. This effect stops until the end of a battle if this module is hit by an attack.",
        "Sacrifice 100 ship HP to launch a blast that deals 300 dmg.If operated by a General Officer, you can also sacrifice 200 ship HP to deal 600 dmg.",
        "When the ship is below 1/3 HP, increase the Total Performance of your ship by +20%. If operated by a General Officer, Total Performance also increases to +40% when below 1/4 HP.",
        "Place a crew member in it to read exactly what its traits do. Takes 10 turns to reload.",
        "Grim Reaper themed.Every time a crew member dies, the damage of this module permanently increases +10, to a maximum of +100 dmg.",
        "Only once, you can switch to a different module layout of your choice. It can’t be separated from its adjacent modules.",
        "Module built by a Biologist from a creature that doesn’t have an exclusive module.Tends to attract enemy attacks.",
        "Recruiters and Businessmen in/adjacent to this module will yield +50 currency after a battle.",
        "Extremely heavy nucleus that can’t be manned.It increases your ship’s HP by 100, and charges adjacent defensive modules 50% faster.Once placed in a slot of the layout, it can’t ever be moved from there.",
        "Once a module is placed adjacent to this one, it can’t be separated, unless someone pukes in a module. When this or adjacent modules get hit by an enemy, it will get stuck, and this module will attract more attacks to this area while taking only 30% dmg.",
        "It uses its long tentacles to pick up items every now and then.",
        "Adjacent crew members will have a chance of gaining the trait Sushi chef.",
        "If a module explodes, absorb energy from the explosion to charge up your modules for 50%.",
        "If a crew member loses HP in this module, it fires a piercing pain blast of 150 dmg into the enemy.",
        "+10 dmg for each crew member with an ailment.",
        "When flooded, injects the water with enhancing drugs that increase performance by 15% of any crew member in this or any other flooded modules.However if this module gets hit, the drugs will instead turn crew members Lunatic.",
        "Both parts always appear as a pair in the shop, for 150 each. Freeze the water around the ship to create an ice barrier that creates a 300 ship HP shield at the beginning of every battle.",
        "Only once, and at the end of a battle, the crew member in it will change to a profession of your choice, and its performance cap will be increased to 150%.",
        "Once per battle, throws one of your items at random to block an enemy attack. If the item was organic sediment, it also inflicts Poisoned status, and if it was shipwreck parts, it deals 50 dmg.",
        "When a module floods, instantly turn it into a Frozen Coffin.",
        "At the end of a battle, earn more currency the less SHP you lost. +100-500 currency from 300-0 SHP lost.",
        "If an enemy attacks this or any adjacent module, it inflicts Frozen status.",
        "Every time you win a battle, +10 to your ship HP, stacks up to 15 times.",
        "You can insert 150 currency in it, and after 20 turns, it will produce a random crew member.",
        "After 30 turns with an item in it, it will produce a copy of that item.",
        "When a module floods, instantly boils away the water to shoot scalding steam at the enemy that deals 200 dmg.Any crew member in the flooded module will take 1 HP dmg.",
        "If one enemy is below 300 HP in a multi-battle, use said enemy as a shield to deter his friends from attack your ship.",
        "Once per battle, during 1 turn, double any Offensive or Defensive effects that your other modules used.",
        "If occupied by the General Officer, increases the Performance of all Cadets by 25%.",
        "Unmanned.The ship will mark the juiciest Nodes nearby in the Node Map.",
        "Unmanned.Pulls an adjacent crew member into its interior, and he will become Stunned unless you pay 200 currency.",
        "Unmanned.Only works when adjacent to 4 crew members of the same profession. When any of them die, this module will replace their Stacking Bonus count.",
        "Modules Adjacent to this one have a 10% chance of changing into a random Organic module at the end of a battle.",
        "Every time you place a new type of professional in this module, it is consumed.If this module consumes all 12 types of professional, it will grant the basic Stacking Bonus of every type of professional, but you can’t receive the bigger Stacking Bonuses.",
        "If you have 100 SHP or less, blast the enemy with a Nuclear Disintegrator that has a 50% chance of obliterating it and healing you for 500 SHP, and a 50% chance of destroying your own ship instead.There is only one per Dive.",
        "-50 dmg. After 10 victorious battles, +70 dmg instead.",
        "Place a Crew Member inside this Module, they will disappear inside it for 20 turns. After this, there’s a 50% chance they come out Lunatic and with 1 Health, and a 50% chance both them and a copy exit the Module with 4 Health each.",
        "Reverse the way Ship Performance works: the lower it is, the more damage the Ship does. Only works if the Crew Member in this module has 10% or less Performance.",
        "At the start of every battle, all of the Crew Members in the ship will become the same Crew Member as one in or adjacent to Person Multiplier. All of your Crew Members are immune to Ailments.",
        "All of your Crew Members have +20% Performance, however, every battle, each of them will have a random Trait effect that doesn’t correspond with their Trait.",
        "All of your Crew Members have +10% Performance, however, every battle, they will all change to a random Profession, but the same one for all.",
        "Your Ship Performance will always be 100%. Once per Crew Member, they will be abducted for 20 turns and then returned with the Reanimated Trait.",
        "This Module can’t be moved from its place in the layout. After 20 turns, the gates open and a Crew Member of a random Profession and the The Chosen One Trait appears.",
        "At the start of every Build Phase, all of your Modules and Crew Members change to completely random ones, but if you achieve 50% or more Ship Performance, it automatically increases another 25%.",
        "At the start of every battle, all of the Modules in the ship will become the same Module as one of the Modules adjacent to Mirroring Diamond. All of your Modules are immune to Flooding.",
        "Every 2 turns, all Crew Members will teleport to other Modules randomly. Every time a different Crew Member teleports into this Module, deal 100 damage to the enemy (resets every battle).",
        "All Crew Members will attack each other, dealing 1 Health damage every 2 turns. Every time a Crew Member loses Health, this Module deals 100 damage to the enemy, and if a Crew Member dies, deals 300 damage instead.",
        "For as long as this module hasn’t been disturbed in battle, gain 1 stacking bonus count for the profession of the crew member inside this module.",
        "If this module is about to explode, or the crew member in it about to die, eject the crew member to the bench while this module is ejected and disappears.",
        "If the enemy hits this module, inflict Asleep status. The crew member in this module starts every battle Sleepy.",
        "If this module is hit, the crew member in it takes the damage twice.",
        "If this module is Water-flooded, there’s no drawbacks and +1HP/4turns.",
        "If this module was hit, produce 1 Tasty fish meal and 100 extra coins at the end of the battle.",
        "Every time the module is hit, the crocodiles will bite the enemy for 100 dmg but lose 1 HP out of a total of 4 HP. After reaching 0 HP it becomes a Dumpster module. If a crew member is placed in this module, they will die but fully heal the crocodiles.",
        "The crew member in this module will have 100% performance, however they will lose 1 HP every 6 turns, and if they die, this and an adjacent module will explode",
        "If the crew member in this module holds an item, you can launch it at the enemy to deal 200 dmg",
        "If the crew member in this module holds an item, you can launch it at the enemy to block and attack",
        "Every time an item is consumed or destroyed, 50% chance of gaining 50 coins and 50% chance of receiving another random item",
        "Once per Dive, eliminate an adjacent map node, and the nodes adjacent to that nodes will become direct paths",
        "For every crew member connected and in line with this module, +5 dmg.",
        "+40 dmg. If at any moment it is not adjacent to 4 crew members, this module explodes.",
        "Electrify this and all Offensive modules chain-connected to this one. 20 damage every time the enemy hits an electrified Offensive module.",
        "Releases Magifish to this and any other water-flooded modules in your ship. Magifish heal their crew member +1HP/4 turns.",
        "If hit, deal 100 damage to the enemy and release Sea Urchins to all adjacent modules that will disappear and deal 100 damage to the enemy if also hit.",
        "+20% performance in adjacent organic modules. Adjacent modules have a 33% chance of becoming Wild at the end of a battle.",
        "Prevents this and adjacent modules from being set on fire.",
        "+10 dmg for each adjacent module that’s set on fire. Every adjacent module has a 25% chance of being set on fire at the start of each battle.",
        "Unmanned. This module is always set on fire. If hit by the enemy, there’s a volcanic explosion that sets on fire all surrounding modules and deals 500 damage to the enemy.",
        "If the enemy hits this module, produce 1 Tasty Fish Meal.",
        "If set on fire, it will produce 1 Tasty Pizza at the end of the battle.",
        "If set on fire, it will produce 1 metal weapon item at the end of the battle.",
        "Activate this module’s effect for it to become Detached, after which it will no longer be targeted by the enemy.",
        "Every 6 turns, each adjacent module will have a 25% chance of becoming Detached.",
        "+40% performance to the crew member in it. At turn 4, this module always becomes detached.",
        "+10 dmg. +10 extra dmg for each Detached module, even if they’re in another node.",
        "Adjacent modules to this one become inactive. For each adjacent module, +50 Ship HP.",
        "If undisturbed and if its crew member is female, at the end of the battle they will have Pregnant as their secondary trait.",
        "If set on fire, +1HP/4turns to this and adjacent crew members, and prevents freezing in these modules too.",
        "Once per battle, you can freeze or defrost the adjacent module to the left.",
        "If this module receives an ally hit, instead deflect the missile to the enemy dealing 200 damage.",
        "If this module is Wild, +40 HP for every Wild module.",
        "Every 2 turns, there’s a 20% chance its crew member swaps places with a nearby module.",
        "+100dmg, but this module is permanently unstable.",
        "+60dmg, but it overheats and every 4 turns, a random adjacent module will be set on fire (70%) or become unstable (30%).",
        "+60dmg. Unless adjacent to an ecrement-flooded or water-flooded module, it'll be set on fire after 4 turns, and then become unstable in another 4 turns.",
        "+40dmg. If the crew member in it has less than 60% performance, this module becomes unstable.",
        "Prevents explosions and fixes unstable in this or any adjacent module.",
        "Detaches at the start of battle, but returns to the ship at the end of the battle.",
        "Activate to un-detach all modules. Items and crew members in this or adjacent modules can’t move from their place during battle.",
        "+100dmg, but every 4 turns, there’s a 50% chance an adjacent module becomes detached.",
        "Shoots a red beam that’s very thin, but the more damaged the module is, the more energy is released and the thicker the beam becomes. +5dmg. +50dmg if this module is damaged. +100dmg if this module is unstable.",
        "CDs regenerate 25% faster if there’s a Wild module adjacent to this one.",
        "If next to a Wild module during battle, produce 1 O2 at the end of battle.",
        "If there’s an adjacent Wild module, at the end of the battle produce one of the following items: Recipe Book (0-10), Book of the Dead (11-20), Ancient Volume of Wisdom (21-30), Lost Page (31-40), Treasure Map (41-50), Love Letter (51-60), Suspicious Magazines (61-70), Military Propaganda (71-80), Notice of Termination (81-90) or University Diploma (91-100).",
        "If this module is Wild, its crew member will throw wooden spears at the enemy, +30dmg.",
        "If this module is Wild, its crew member will be protected by branches from the first enemy hit each battle.",
        "This module is permanently set on fire. At the end of each battle, gain a random bad quality item that will last for 1 battle.",
        "This module is permanently set on fire. Unmanned. If hit by the enemy, inflict burn // deal 200 damage and each adjacent module will have a 50% chance of being set on fire.",
        "This module is permanently wild. The crew member in it, at the end of the battle and once per dive, will receive Summoning Rune, Human Skeleton or Pendant of Cursed Water. ",
        "This module is permanently wild. Unmanned. At the start of each battle, Vicious Dinosaur appears in this module until the end of the battle.",
        "This module is permanently damaged. If the enemy hits this or an adjacent module, throw a torpedo that deals 150 damage.",
        "This module is permanently damaged. If the enemy hits this or an adjacent module, deflect the attack once per battle.",
        "This module is permanently damaged. At the end of each battle, there’s a 50% chance you gain a random bad quality item that will last for 1 battle.",
        "Unmanned. This module is permanently frozen. If surrounded by 4 water-flooded modules, it permanently grows a massive iceberg, and if this or any adjacent modules are hit by the enemy, freeze the enemy // blow a blizzard that deals 300 dmg.",
        "Unmanned. If an adjacent module is water-flooded, it becomes frozen after 2 turns. Every time an enemy hits a frozen module connected to this one, freeze the enemy // deal 300 dmg.",
        "Unmanned. This module is permanently excrement-flooded. If hit, excrement-floods any adjacent module to the left and right.",
        "Unmanned. While this module is surrounded by 4 water-flooded modules, it will be occupied by Atlantis Elder until the end of the battle.",
        "If this or an adjacent module is hit by the enemy, the catapult fires the crew member in this module, who dies, dealing 300 dmg to the enemy.",
        "The crew member inside this module will have -40% performance as they will be busy preparing sushi, but they will produce one Tasty Fish Meal every 6 turns.",
        "When a crew member in or adjacent to this module is inflicted with an Ailment that isn’t Lunatic, reroll it to another Ailment except for Lunatic.",
        "When this or an adjacent module is inflicted with wild, set on fire, water-flooded, excrement-flooded, frozen or detached, reroll this status to another one of these statuses.",
        "Bubbles that may form automatically adjacent to crew members that fart. Explodes after being hit, and a Crew Member in it will become Sick. If hit by an enemy, they will be inflicted Poisoned status.",
        "Bubbles that may form automatically adjacent to crew members that are heavy smokers. Explodes after being hit, and a Crew Member in it will become Sick. If hit by an enemy, they will be inflicted Poisoned status.",
        "If there was a crew member in a module when a Frozen Coffin is formed, the crew member is immune to damage but Frozen. If an enemy hits a Frozen coffin, there’s a 50% chance to inflict Frozen status.",
        "This module can’t be bought or crafted. It is only born by leaving an available space surrounded by 4 organic modules, after which it cannot be separated from its 4 adjacent modules. Every battle, Eye of the Calamity uses one offensive or defensive abyssal creature effect (those present in Organic Mega-Modules).",
        "This module can’t be bought or crafted. It is only born by having a Pearl equipped inside an Organic module, that then absorbs the item and transforms into Pearlcore, which is unmanned so that holder is moved to the bench. Once per battle, heal everyone 1HP and +100 Ship HP.",
        "Place next to the Captain to reveal the contents of all nodes in the current level. Once placed, it cannot be moved from its slot.",
        "Old and damaged module that will suffer a random module status at the start of each battle.",
        "Unmanned, indestructible,occupies 4 modules in a row and has to be placed at the very bottom of the slot layout. For as long as its in this position, halve O2 consumption, and increase your Ship Health by 300 HP.",
        "All modules in this row charge up 50% faster.",
        "Once per battle in turn 4, fire a nuclear blast at the enemy that deals 300 damage, but it sets on fire all modules in this row.",



};

    public int[] cooldown = new int[235] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                            0, 0, 30, 0, 0, 0, 0, 0, 0, 0,
                                            0, 0, 0, 0, 0, 0, 0, 10, 0, 0,
                                            0, 0, 2, 0, 0, 0, 0, 4, 0, 0,
                                            0, 0, 0, 30, 0, 0, 0, 20, 0, 2,
                                            0, 0, 20, 20, 0, 0, 0, 0, 0, 0,
                                            0, 0, 0, 0, 0, 0, 3, 3, 0, 0,
                                            0, 0, 0, 0, 0, 0, 0, 0, 20, 0,
                                            0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
                                            12, 15, 30, 0, 4, 0, 0, 30, 0, 0,
                                            //Next is 101
                                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                            0, 0, 0, 0, 0, 0, 0, 10, 0, 0,
                                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                            0, 0, 0, 0, 0, 0, 0, 20, 0, 0,
                                            0, 0, 0, 0, 0, 0, 0, 0, 0, 100,
                                            20, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                            30, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                            //Next is 201
                                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
                                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                            0, 0, 0, 0, 0
    };

    public ModuleType[] moduleType = new ModuleType[235] { (ModuleType)1, (ModuleType)1, (ModuleType)1, (ModuleType)0, (ModuleType)1, (ModuleType)2, (ModuleType)2, (ModuleType)4, (ModuleType)4, (ModuleType)3,
    (ModuleType)1, (ModuleType)0, (ModuleType)3, (ModuleType)2, (ModuleType)0, (ModuleType)0, (ModuleType)3, (ModuleType)3, (ModuleType)3, (ModuleType)0, (ModuleType)2, (ModuleType)2, (ModuleType)3, (ModuleType)0, (ModuleType)2,
    (ModuleType)3, (ModuleType)0, (ModuleType)0, (ModuleType)0, (ModuleType)3, (ModuleType)3, (ModuleType)1, (ModuleType)3, (ModuleType)0, (ModuleType)1, (ModuleType)0, (ModuleType)0, (ModuleType)1, (ModuleType)0, (ModuleType)3,
    (ModuleType)3, (ModuleType)3, (ModuleType)3, (ModuleType)0, (ModuleType)2, (ModuleType)4, (ModuleType)4, (ModuleType)4, (ModuleType)2, (ModuleType)4, (ModuleType)4, (ModuleType)3, (ModuleType)4, (ModuleType)4, (ModuleType)2,
    (ModuleType)0, (ModuleType)2, (ModuleType)2, (ModuleType)1, (ModuleType)2, (ModuleType)4, (ModuleType)1, (ModuleType)1, (ModuleType)1, (ModuleType)1, (ModuleType)0, (ModuleType)1, (ModuleType)2, (ModuleType)3, (ModuleType)3,
    (ModuleType)2, (ModuleType)3, (ModuleType)4, (ModuleType)4, (ModuleType)2, (ModuleType)4, (ModuleType)4, (ModuleType)3, (ModuleType)4, (ModuleType)4, (ModuleType)1, (ModuleType)2, (ModuleType)4, (ModuleType)0, (ModuleType)2,
    (ModuleType)1, (ModuleType)4, (ModuleType)0, (ModuleType)3, (ModuleType)0, (ModuleType)3, (ModuleType)4, (ModuleType)3, (ModuleType)4, (ModuleType)1, (ModuleType)1, (ModuleType)0, (ModuleType)5, (ModuleType)4, (ModuleType)4,
    (ModuleType)1, (ModuleType)0, (ModuleType)1, (ModuleType)3, (ModuleType)4, (ModuleType)4, (ModuleType)4, (ModuleType)4, (ModuleType)3, (ModuleType)3, (ModuleType)2, (ModuleType)1, (ModuleType)0, (ModuleType)2, (ModuleType)2,
    (ModuleType)1, (ModuleType)1, (ModuleType)3, (ModuleType)1, (ModuleType)4, (ModuleType)0, (ModuleType)4, (ModuleType)2, (ModuleType)2, (ModuleType)0, (ModuleType)4, (ModuleType)3, (ModuleType)1, (ModuleType)1, (ModuleType)3,
    (ModuleType)2, (ModuleType)4, (ModuleType)2, (ModuleType)2, (ModuleType)4, (ModuleType)2, (ModuleType)2, (ModuleType)3, (ModuleType)3, (ModuleType)1, (ModuleType)2, (ModuleType)4, (ModuleType)4, (ModuleType)4, (ModuleType)4,
    (ModuleType)4, (ModuleType)0, (ModuleType)4, (ModuleType)1, (ModuleType)4, (ModuleType)4, (ModuleType)3, (ModuleType)4, (ModuleType)4, (ModuleType)4, (ModuleType)4, (ModuleType)4, (ModuleType)4, (ModuleType)4, (ModuleType)3,
    (ModuleType)4, (ModuleType)3, (ModuleType)3, (ModuleType)0, (ModuleType)4, (ModuleType)2, (ModuleType)4, (ModuleType)4, (ModuleType)3, (ModuleType)1, (ModuleType)2, (ModuleType)3, (ModuleType)3, (ModuleType)1, (ModuleType)1,
    (ModuleType)1, (ModuleType)0, (ModuleType)0, (ModuleType)0, (ModuleType)4, (ModuleType)1, (ModuleType)0, (ModuleType)4, (ModuleType)4, (ModuleType)4, (ModuleType)3, (ModuleType)3, (ModuleType)3, (ModuleType)1, (ModuleType)2,
    (ModuleType)3, (ModuleType)2, (ModuleType)3, (ModuleType)1, (ModuleType)2, (ModuleType)4, (ModuleType)1, (ModuleType)1, (ModuleType)1, (ModuleType)1, (ModuleType)3, (ModuleType)4, (ModuleType)3, (ModuleType)1, (ModuleType)1,
    (ModuleType)3, (ModuleType)3, (ModuleType)3, (ModuleType)1, (ModuleType)2, (ModuleType)3, (ModuleType)1, (ModuleType)4, (ModuleType)4, (ModuleType)1, (ModuleType)2, (ModuleType)3, (ModuleType)4, (ModuleType)3, (ModuleType)4,
    (ModuleType)4, (ModuleType)1, (ModuleType)4, (ModuleType)4, (ModuleType)4, (ModuleType)4, (ModuleType)4, (ModuleType)2, (ModuleType)0, (ModuleType)0, (ModuleType)4, (ModuleType)0, (ModuleType)0, (ModuleType)3, (ModuleType)3
};

    public string[] req = new string[235] { "1", "1", "0", "Needs to be placed in the first column of your Layout.", "1", "1", "0", "0", "0", "1", "1", "1", "0", "1", "1", "1", "1", "1", "0", "0", "0", "0", "1", "1",
     "Only works if adjacent to a Defensive module.", "0", "1", "1",
     "1", "1", "1", "1", "1", "1", "Only works if adjacent to another attack module.", "Can only be placed in the very last column of the Layout.",
     "0", "1", "1", "0", "0", "0", "0", "1", "0", "0", "1", "0", "1", "0", "0", "0", "1", "0", "1", "0", "1", "0", "0", "0", "1", "0", "1", "0", "1", "0", "0", "0", "1", "1", "1", "0", "0", "0", "1", "0", "1", "0", "1", "1",
     "0", "0", "Only works when adjacent to two offensive and two defensive modules.", "0", "Only works when adjacent to 4 defensive modules.", "Only works when adjacent to 4 offensive modules.", "0", "1", "0", "1", "1", "1",
     "1", "1", "1", "0", "1", "0", "1", "0", "1", "1", "0", "1", "0", "0", "1", "0", "1", "0", "0", "0", "0", "1", "1", "1", "1", "1", "1", "Must be adjacent to all other 4 modules types.", "0", "1", "0", "0", "1", "1",
     "0", "1", "1", "0", "One must be placed in the highest row of the Layout, and the other in the lowest row.", "0", "1", "0",
     "0", "0", "1", "0", "1", "0", "1", "Must be adjacent to the Captain", "Must be adjacent to the Captain.", "Must be adjacent to the Captain.", "0", "Only works when adjacent to 4 crew members of the same profession.",
     "0", "0", "0", "1", "1", "0", "Only works when adjacent to 4 crew Members.", "0", "0", "0", "0", "0", "Only works when adjacent to 4 Modules.", "0", "0", "1", "1", "0", "0", "1", "1", "1", "0", "1", "0",
    "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0", "0", "0", "Must be placed in the periphery of the layout.", "1", "1", "0", "1", "1", "1", "0", "1", "1", "1", "1", "1", "0", "1", "1", "1",
    "1", "1", "1", "1", "1", "0", "1", "0", "1", "0", "0", "0", "0", "1", "0", "1", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "1", "1"};

    public ModuleRequirements[] randomReq = new ModuleRequirements[13] { (ModuleRequirements)0, (ModuleRequirements)1, (ModuleRequirements)2, (ModuleRequirements)3, (ModuleRequirements)4, (ModuleRequirements)5,
    (ModuleRequirements)6, (ModuleRequirements)7, (ModuleRequirements)8, (ModuleRequirements)9, (ModuleRequirements)10, (ModuleRequirements)11, (ModuleRequirements)12};

    public int[] modulePrice = new int[235] {200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
                                            200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
                                            200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
                                            200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
                                            200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
                                            200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
                                            200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
                                            200, 200, 100, 100, 200, 200, 200, 200, 200, 200,
                                            200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
                                            200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
                                            //101 is next
                                            200, 200, 200, 200, 100, 100, 200, 100, 200, 200,
                                            200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
                                            200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
                                            300, 200, 200, 200, 200, 200, 200, 200, 200, 200,
                                            200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
                                            200, 500, 500, 500, 500, 500, 500, 500, 500, 500,
                                            500, 200, 200, 200, 200, 200, 200, 200, 200, 200,
                                            200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
                                            200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
                                            200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
                                            //201 is next
                                            200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
                                            200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
                                            200, 200, 200, 200, 200,
                                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };

    public string[] typeStacking = new string[6] { "Effects based on creatures, sometimes not hollow and therefore autonomous. There can only be 1 of each type of Organic Module in the ship. \n Organic A modules are available in commerce. \n Organic B modules are exclusive to 4x Biologist stacking bonus. \n Organic M modules are Mega-Modules and exclusive to 8x Biologist. \n 4x = random crew members will soon turn into marine abominations (Monstrous trait). The more organic modules, the more transformations.",
        "Cause & encourage low ship HP, often interact with GO and Cadets. \n 2x = 10% chance your basic attack becomes a shell-destroying nuke. \n 4x = 20 % chance your basic attack becomes a shell-destroying nuke. 6x = 30 % chance your basic attack becomes a shell-destroying nuke.",
        "Cause & encourage high ship HP, stalling (combo with charge bars), and having a fat ship with lots of modules. \n 2x = +10 ship HP for every module in your ship. \n 4x = +20 ship HP for every module in your ship. \n 6x = +30 ship HP for every module in your ship.",
        "Technological effects, item-transformed effects. \n 4x = after a battle, you can transform 1 basic item. \n 8x = after a battle, you can transform 1 rare item.",
        "Niche and unique effects that can fit into any ship. \n 6x = each battle, 1 random module with a random crew member in it are called for assistance and appear in a random available Layout Slot, and they will last until end of combat. \n 10x = each battle, 2 random module with a random crew member in it are called for assistance and appear in a random available Layout Slot, and they will last until end of combat.",
        "Special type of module. There's only a few of these, and their functionality varies. Doesn't have a stacking bonus."
        };

}
